esp32_serial_baro:
  ros__parameters:
    serial_port: /dev/ttyACM1
    output_mode: base-relative
    frequency: 5.0
    base_ip: 192.168.100.42
    default_local_pressure: 1004.0
    longitude: 121.6
    latitude: 31.68
    cali_offsets:
      E8_3D_C1_F1_A0_A8:
        pressure_offset: -0.0049
        temperature_offset: -0.1449
        linear_factor: 1.0
      24_EC_4A_01_43_20:
        pressure_offset: 0.0049
        temperature_offset: 0.1449
        linear_factor: 1.0
